<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Slideshow
 * @author     Suporte <suporte@inovarti.com.br>
 */
$config = Mage::getStoreConfig('slideshow/config');
$action = Mage::app()->getFrontController()->getRequest()->getActionName();
if ($config['enabled']) {
    $show = true;
    if ($show) {
        $slides = $this->getSlides();
        ?>
        <div id="HomeCarousel" class="carousel slide">
            <div class="container">
                <div class="row">
                    <?php if ($config['control_nav']) : ?>
                        <ol class="carousel-indicators">
                            <?php
                            foreach ($slides as $k => $s) {
                                ?>
                                <li data-target="#HomeCarousel" data-slide-to="<?php echo $k - 1; ?>" <?php if ($k == 1) echo 'class="active"'; ?>></li>
                                <?php
                            }
                            ?>
                        </ol>
                    <?php endif;
                    ?>
                    <div class="carousel-inner">
                        <?php
                        foreach ($slides as $k => $s) {
                            ?>
                            <?php if (!empty($s['image'])) : ?>
                                <div class="item <?php if ($k == 1) echo 'active'; ?>"
                                     <?php
                                            echo (empty($s['backgroundimage']) ? '' :
                                                        'style="
                                                                background-image: "'.$s['backgroundimage'].'";
                                                                background-color:  "'.$s['color'].'";
                                                                background-size: "'.$s['backgroundsize'].'";
                                                                background-position: "'.$s['backgroundposition'].'";
                                                                background-repeat:  "'.$s['backgroundrepeat'].'";"'
                                                    ;
                                     ?>
                                    >
                                    <a href="<?php echo ( empty($s['slide_link']) ? '' : '' . $s['slide_link'] . '' ); ?>" <?php echo ( empty($s['slide_link']) ? '' : 'onclick="window.location=\'' . $s['slide_link'] . '\'"' ); ?> title="<?php echo $s['slide_title']; ?>">
                                        <img src="<?php echo Mage::getBaseUrl('media') . $s['image'] ?>" alt="<?php echo $s['slide_title']; ?>" height="<?php echo (is_numeric($config['height']) ? $config['height'] : 'auto' ); ?>"/>
                                    </a>
                                </div>
                            <?php endif; ?>
                            <?php
                        }
                        ?>
                    </div>
                    <!-- Carousel nav -->
                    <?php if ($config['direction_nav']): ?>
                        <a class="carousel-control left" href="#HomeCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                        <a class="carousel-control right" href="#HomeCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                        <?php endif; ?>
                </div>
            </div>
        </div>
        <script>
            jQuery('#HomeCarousel').carousel({
                interval: <?php echo $config['interval']; ?>, wrap: <?php echo ( in_array($config['wrap'], array('true', 'false')) ? $config['wrap'] : 'false' ); ?>
            });
            jQuery('.carousel-inner > div.item').eq(0).addClass('active');
        </script>
        <?php
    }
}
?>