<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Slideshow
 * @author     Suporte <suporte@inovarti.com.br>
 */
$config = Mage::getStoreConfig('slideshow/config');
$action = Mage::app()->getFrontController()->getRequest()->getActionName();
if ($config['enabled']) {
    $show = true;
    if ($show) {
        $slides = $this->getSlides();
        ?>
        <div id="HomeCarousel" class="carousel slide">  
            <?php if ($config['control_nav']) : ?>
                <ol class="carousel-indicators">
                    <?php
                    $i = 0;
                    foreach ($slides as $s) {
                        ?>
                        <li data-target="#HomeCarousel" data-slide-to="<?php echo $i ?>" <?php if ($i == 0) echo 'class="active"'; ?>></li>
                        <?php
                        $i++;
                    }
                    ?>
                </ol>
            <?php endif;
            ?>
            <div class="carousel-inner">  
                <?php
                foreach ($slides as $s) {
                    $style = $content = '';
                    $attr = 'data-img-height="0"';
                    if (!empty($s['image'])) {
                        $imgSize = getimagesize(Mage::getBaseDir('media') . '/' . $s['image']);
                        if ($imgSize) {
                            $style = "background:url('" . Mage::getBaseUrl('media') . $s['image'] . "') 50% 0 no-repeat;";
                            $attr = 'data-img-height="' . $imgSize[1] . '"';
                        }
                    }
                    if (!empty($s['slide_width'])) {
                        $content = 'style="width:' . $s['slide_width'] . 'px;"';
                    }
                    ?>
            <?php if (!empty($s['image'])) : ?>
                        <div class="item">
                            <a href="<?php echo ( empty($s['slide_link']) ? '' : '' . $s['slide_link'] . '' ); ?>" <?php echo ( empty($s['slide_link']) ? '' : 'onclick="window.location=\'' . $s['slide_link'] . '\'"' ); ?> title="<?php echo $s['slide_title']; ?>">
                                <img class="small_image main-image" src="<?php echo Mage::getBaseUrl('media') . $s['image'] ?>" alt="<?php echo $s['slide_title']; ?>" <?php echo (is_numeric($config['height']) ? $config['height'] : 'auto' ); ?>/>
                            </a>
                        </div>
                    <?php endif; ?>
                    <?php
                }
                ?>
            </div>  
            <!-- Carousel nav -->  
        <?php if ($config['direction_nav']): ?>
                <a class="carousel-control left" href="#HomeCarousel" data-slide="prev">‹</a>  
                <a class="carousel-control right" href="#HomeCarousel" data-slide="next">›</a>  
        <?php endif; ?>
        </div>  
        <script>
            jQuery('#HomeCarousel').carousel({
                interval: <?php echo $config['interval']; ?>,
                wrap: <?php echo ( in_array($config['wrap'], array('true', 'false')) ? $config['wrap'] : 'false' ); ?>
            });
            jQuery('.carousel-inner > div.item').eq(0).addClass('active');
        </script>
        <?php
    }
}
?>