<?php
$config = Mage::getStoreConfig('slideshow/config');
$route = Mage::app()->getFrontController()->getRequest()->getRouteName();
$action = Mage::app()->getFrontController()->getRequest()->getActionName();
if ( $config['enabled'] ) {
    $show = true;
    if ( $config['show'] == 'home' ) {
        $show = false;
        $page = Mage::app()->getFrontController()->getRequest()->getRouteName();

        if($page =='cms'){
            $cmsSingletonIdentifier = Mage::getSingleton('cms/page')->getIdentifier();
            $homeIdentifier = Mage::app()->getStore()->getConfig('web/default/cms_home_page');
            if($cmsSingletonIdentifier === $homeIdentifier){
                $show = true;
            }
        }
    }
    if ( $show && ($route == 'customer' && ($action == 'login' || $action == 'forgotpassword' || $action == 'create')) ) {
        $show = false;
    }
    if ( $show ) {
        ?>
    <div id="hp_carousel" class="carousel">
        <div class="view-content">
            <?php
                $slides = $this->getSlides();
                foreach($slides as $s) {
                    $style = $content = '';
                    $attr = 'data-img-height="0"';
                    if ( !empty($s['image']) ) {
                        $imgSize = getimagesize(Mage::getBaseDir('media') .'/'. $s['image']);
                        if ($imgSize) {
                            $style = "background:url('". Mage::getBaseUrl('media') . $s['image'] . "') 50% 0 no-repeat;";
                            $attr = 'data-img-height="'.$imgSize[1].'"';
                        }
                    }
                    if ( !empty($s['slide_width']) ) {
                        $content = 'style="width:'.$s['slide_width'].'px;"';
                    }
                    ?>
                <div class="wrapCarousel carousel-item">
                    <div class="carousel-image">
                            <?php if ( !empty($s['image']) ) : ?>
                            <a href="<?php echo ( empty($s['slide_link']) ? '' : ''.$s['slide_link'].'' ); ?>" <?php echo ( empty($s['slide_link']) ? '' : 'onclick="window.location=\''.$s['slide_link'].'\'"' ); ?> title="<?php echo $s['slide_title']; ?>"><img class="small_image main-image" src="<?php echo Mage::getBaseUrl('media') . $s['image'] ?>" alt="<?php echo $s['slide_title']; ?>" width="1170" height="395"/></a>
                            <?php endif; ?>
                    </div>
                </div>
                <?php
                }
                ?>
        </div>
    </div>
    <?php } //if ( $show ) { ?>
<?php } //if ( $config['enabled'] ) { ?>